// Mock profiling turns — each corresponds to one user message during the PROFILING phase.
// The last turn has is_complete: true, which signals the transition to CONVERSING.

export const MOCK_PROFILING_TURNS = [
  {
    phase: 'PROFILING',
    state: 'AMOUNT',
    reply: "Aoa! I'm Gullak. How much are you thinking of investing each month?",
    options: {
      state: 'AMOUNT',
      options: [
        { label: 'Rs 5,000',  value: 'Rs 5,000 per month'  },
        { label: 'Rs 10,000', value: 'Rs 10,000 per month' },
        { label: 'Rs 20,000', value: 'Rs 20,000 per month' },
        { label: 'Rs 50,000', value: 'Rs 50,000 per month' },
      ],
    },
    is_complete: false,
  },
  {
    phase: 'PROFILING',
    state: 'HORIZON',
    reply: "Got it — Rs 20,000 a month, noted! How long can you leave this money invested?",
    options: {
      state: 'HORIZON',
      options: [
        { label: '1 year',    value: '1 year'    },
        { label: '3 years',   value: '3 years'   },
        { label: '5 years',   value: '5 years'   },
        { label: '10+ years', value: '10+ years' },
      ],
    },
    is_complete: false,
  },
  {
    phase: 'PROFILING',
    state: 'RISK',
    reply: "13 years — great, that gives us a lot of flexibility. If your investment dropped 20% in a bad year, how would you feel?",
    options: {
      state: 'RISK',
      options: [
        { label: "I'd panic",         value: "I would panic — I need my money safe"       },
        { label: "I'd stay calm",     value: "I'd stay calm and wait it out"              },
        { label: "I'd invest more",   value: "I'd see it as a chance to invest more"      },
      ],
    },
    is_complete: false,
  },
  {
    phase: 'PROFILING',
    state: 'SHARIAH',
    reply: "Medium risk, understood. Do you want Shariah-compliant funds only?",
    options: {
      state: 'SHARIAH',
      options: [
        { label: 'Shariah only',    value: 'Yes, Shariah-compliant funds only'         },
        { label: 'Conventional',    value: 'No, conventional funds are fine'           },
        { label: 'No preference',   value: 'No preference — show me the best options' },
      ],
    },
    is_complete: false,
  },
  {
    phase: 'PROFILING',
    state: 'CATEGORY',
    reply: "No problem! Any particular type of fund you have in mind?",
    options: {
      state: 'CATEGORY',
      options: [
        { label: 'Equity (stocks)',  value: 'Equity — I want exposure to stocks'           },
        { label: 'Money Market',     value: 'Money Market — safer, lower return'           },
        { label: 'Balanced',         value: 'Balanced — mix of stocks and bonds'           },
        { label: 'No preference',    value: 'No preference — you decide what fits my goal' },
      ],
    },
    is_complete: false,
  },
  {
    phase: 'PROFILING',
    state: 'LIQUIDITY',
    reply: "Almost there! Might you need to access this money before the 13 years are up?",
    options: {
      state: 'LIQUIDITY',
      options: [
        { label: 'Not likely',     value: 'Unlikely — I can keep it invested the full time' },
        { label: 'Maybe in 2–3y',  value: 'Maybe in 2–3 years if something comes up'        },
        { label: 'Could need soon', value: 'I might need some of it sooner'                 },
      ],
    },
    is_complete: false,
  },
  {
    phase: 'PROFILING',
    state: 'COMPLETE',
    reply: "Perfect — that's everything I need. Running the analysis now...",
    options: null,
    is_complete: true,
  },
]

// Mock CONVERSING response — matches the real backend schema exactly.
// Decimals for returns/ratios, expense_ratio already in %.
export const MOCK_CONVERSING_RESPONSE = {
  phase: 'CONVERSING',
  reply:
    "Based on your goal of saving for your daughter's university education over 13 years, I've found your top pick: **MCB Pakistan Stock Market Fund** — a consistent performer with an 8.95 Gullak Score. It captured 104% of market gains but only 91% of losses, making it ideal for long-horizon goals.",
  narration: [
    {
      anchor: 'top_pick',
      text:
        'MCB Pakistan Stock Market Fund ranks first with a Gullak Score of 8.95. It scored a perfect 10 for consistency — meaning it delivers steady, predictable results across market cycles, exactly what you need for a 13-year goal.',
    },
    {
      anchor: 'comparison',
      text:
        'NBP Financial Sector Fund delivered higher absolute returns (74.6% last year) but comes with deeper drawdowns. MCB Opportunity Fund offers equity-like returns with half the volatility — a good middle ground if you want smoother ride.',
    },
    {
      anchor: 'capture',
      text:
        'When the KSE-100 went up Rs 100, MCB Stock Market went up Rs 104. When it dropped Rs 100, this fund only dropped Rs 91. That asymmetry compounds powerfully over 13 years.',
    },
    {
      anchor: 'goal',
      text:
        'With Rs 20,000/month over 156 months, your corpus grows substantially. The top three funds delivered 52–77% annualized over three years — well ahead of the category average of 46.9%.',
    },
  ],
  education: null,
  shortlist: {
    investor_summary: "Saving for daughter's university education, 13-year horizon, medium risk, no Shariah preference.",
    filters_applied: {
      category: ['Equity', 'Asset Allocation', 'Fund of Funds'],
      shariah_flag: null,
      fund_type: 'Open-End, Dedicated Equity, ETF',
      exclude_null_return_1y: true,
    },
    universe_after_filter: 45,
    scoring_weights: {
      performance_score: 0.25,
      risk_score: 0.2,
      cost_score: 0.2,
      consistency_score: 0.2,
      capture_score: 0.15,
    },
    shortlist: [
      {
        rank: 1,
        fund_id: '12724',
        fund_name: 'MCB Pakistan Stock Market Fund',
        amc_name: 'MCB Investment Management Limited',
        category: 'Equity',
        shariah_flag: false,
        fundlens_score: 8.95,
        scores_used: ['performance_score', 'risk_score', 'cost_score', 'consistency_score', 'capture_score'],
        scores_missing: [],
        return_1y: 0.5075,
        return_3y_ann: 0.642049,
        sharpe_ratio: 1.677294,
        sortino_ratio: 3.256299,
        volatility_monthly: 0.069273,
        max_drawdown: -0.23229,
        max_drawdown_recovery_days: null,
        beta: 1.021971,
        expense_ratio: 4.18,
        expense_vs_category: 0.283333,
        front_end_load: 0.0,
        alpha: 0.148468,
        upside_capture_ratio: 103.952633,
        downside_capture_ratio: 91.231963,
        performance_score: 9.62,
        risk_score: 9.31,
        cost_score: 6.19,
        consistency_score: 10.0,
        capture_score: 9.62,
        selection_reason:
          'Top-ranked by composite fundlens_score (8.95). Exceptional all-around performer with highest consistency_score (10.0) and balanced market capture.',
      },
      {
        rank: 2,
        fund_id: '13081',
        fund_name: 'NBP Financial Sector Fund',
        amc_name: 'NBP Fund Management Limited',
        category: 'Equity',
        shariah_flag: false,
        fundlens_score: 8.43,
        scores_used: ['performance_score', 'risk_score', 'cost_score', 'consistency_score', 'capture_score'],
        scores_missing: [],
        return_1y: 0.7456,
        return_3y_ann: 0.774316,
        sharpe_ratio: 1.79583,
        sortino_ratio: 2.228825,
        volatility_monthly: 0.102975,
        max_drawdown: -0.297571,
        max_drawdown_recovery_days: 308,
        beta: 1.025251,
        expense_ratio: 3.56,
        expense_vs_category: -0.336667,
        front_end_load: 0.0,
        alpha: 0.385753,
        upside_capture_ratio: 53.22289,
        downside_capture_ratio: 40.575543,
        performance_score: 10.0,
        risk_score: 4.81,
        cost_score: 8.27,
        consistency_score: 9.65,
        capture_score: 9.25,
        selection_reason:
          'Highest absolute returns (74.6% 1Y). Sector-focused with strong alpha generation and exceptional downside protection.',
      },
      {
        rank: 3,
        fund_id: '12747',
        fund_name: 'MCB Pakistan Opportunity Fund',
        amc_name: 'MCB Investment Management Limited',
        category: 'Asset Allocation',
        shariah_flag: false,
        fundlens_score: 8.25,
        scores_used: ['performance_score', 'risk_score', 'cost_score', 'consistency_score', 'capture_score'],
        scores_missing: [],
        return_1y: 0.5221,
        return_3y_ann: 0.614452,
        sharpe_ratio: 2.317569,
        sortino_ratio: 4.974676,
        volatility_monthly: 0.051954,
        max_drawdown: -0.186025,
        max_drawdown_recovery_days: null,
        beta: 0.651219,
        expense_ratio: 4.31,
        expense_vs_category: 0.287333,
        front_end_load: 0.0,
        alpha: 0.255226,
        upside_capture_ratio: 64.337567,
        downside_capture_ratio: 55.853424,
        performance_score: 10.0,
        risk_score: 8.07,
        cost_score: 4.21,
        consistency_score: 10.0,
        capture_score: 8.62,
        selection_reason:
          'Best risk-adjusted returns (Sharpe 2.32). Asset allocation strategy delivers equity-like returns with half the volatility.',
      },
      {
        rank: 4,
        fund_id: '12979',
        fund_name: 'JS Large Cap Fund',
        amc_name: 'JS Investments Limited',
        category: 'Equity',
        shariah_flag: false,
        fundlens_score: 7.48,
        scores_used: ['performance_score', 'risk_score', 'cost_score', 'consistency_score', 'capture_score'],
        scores_missing: [],
        return_1y: 0.3104,
        return_3y_ann: 0.528021,
        sharpe_ratio: 0.916051,
        sortino_ratio: 1.518002,
        volatility_monthly: 0.064727,
        max_drawdown: -0.254404,
        max_drawdown_recovery_days: null,
        beta: 0.986421,
        expense_ratio: 4.36,
        expense_vs_category: 0.463333,
        front_end_load: 0.0,
        alpha: -0.039795,
        upside_capture_ratio: 97.290296,
        downside_capture_ratio: 110.059953,
        performance_score: 7.75,
        risk_score: 7.58,
        cost_score: 5.15,
        consistency_score: 8.62,
        capture_score: 8.5,
        selection_reason: 'Diversification from a third AMC. Large-cap focus with balanced market capture.',
      },
      {
        rank: 5,
        fund_id: '12720',
        fund_name: 'MCB Pakistan Asset Allocation Fund',
        amc_name: 'MCB Investment Management Limited',
        category: 'Asset Allocation',
        shariah_flag: false,
        fundlens_score: 7.12,
        scores_used: ['performance_score', 'risk_score', 'cost_score', 'consistency_score', 'capture_score'],
        scores_missing: [],
        return_1y: 0.3612,
        return_3y_ann: 0.529961,
        sharpe_ratio: 1.093262,
        sortino_ratio: 1.736594,
        volatility_monthly: 0.067649,
        max_drawdown: -0.230268,
        max_drawdown_recovery_days: null,
        beta: 0.934046,
        expense_ratio: 4.42,
        expense_vs_category: 0.397333,
        front_end_load: 0.0,
        alpha: 0.024024,
        upside_capture_ratio: 69.884984,
        downside_capture_ratio: 92.838556,
        performance_score: 9.31,
        risk_score: 6.79,
        cost_score: 3.57,
        consistency_score: 8.71,
        capture_score: 6.54,
        selection_reason: 'Tactical asset allocation with strong performance score and controlled volatility.',
      },
    ],
    category_stats: {
      Equity: {
        fund_count: 27,
        return_1y_median: 0.28905,
        expense_ratio_median: 4.18,
        sharpe_ratio_median: 0.639976,
      },
    },
    risk_free_rate: 0.105001,
  },
  reanalyzed: false,
}
